definitions:
  domain.Task:
    properties:
      checkbox:
        type: boolean
      createdAt:
        type: string
      id:
        type: integer
      text:
        type: string
      updatedAt:
        type: string
    type: object
  gin.H:
    additionalProperties: {}
    type: object
  handlers.PostTask:
    properties:
      checkbox:
        type: boolean
      text:
        type: string
    type: object
  handlers.UpdateRequest:
    properties:
      checkbox:
        type: boolean
      text:
        type: string
    required:
    - text
    type: object
info:
  contact: {}
paths:
  /tasks:
    get:
      description: Get a list of all tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: New_Task
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.PostTask'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      description: delete a task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: delete a task
      tags:
      - tasks
    patch:
      consumes:
      - application/json
      description: Update the task with the given ID.
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update_Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a task
      tags:
      - tasks
swagger: "2.0"
